package it.polimi.ingsw.view.cli;

public enum ViewableId {
    START_TEXT, WIN_TEXT, YOUR_TURN_TEXT, WELCOME_TEXT, DASHBOARD_VIEWABLE, TEST,

    COFFER, WAREHOUSE, PAYCHECK_STRONGBOX, PAYCHECK_DEPOTS,
    FAITH_TRACK, MARKETPLACE, DEVELOPMENT_GRID,
    DEVELOPMENT_CARD, DEVELOPMENT_SPACE1, DEVELOPMENT_SPACE2, DEVELOPMENT_SPACE3,
    LEADER1, LEADER2,
    LEADER_PICK1, LEADER_PICK2, LEADER_PICK3, LEADER_PICK4,
    ACTIVE_PRODUCTIONS,
    UNASSIGNED_MARBLES,
    BASE_PRODUCTION,
    LEADERCARDSPACE,
    LEADERPICK
}
